ARG BASEIMAGE=docker/compose:1.24.1
FROM $BASEIMAGE

ENTRYPOINT []

RUN apk add --no-cache python3 make bash jq fish git

COPY --from=docker:latest /usr/local/bin/docker /usr/local/bin/docker

ENV PS1="\h:\w\$ "
CMD bash

ARG YQ_BIN_VERSION=2.4.0
RUN wget "https://github.com/mikefarah/yq/releases/download/${YQ_BIN_VERSION}/yq_linux_amd64" -O /usr/local/bin/yq

RUN pip3 --no-cache install awscli poetry codecov
