ARG BASEIMAGE=docker/compose:1.24.1
FROM $BASEIMAGE as baseimage

RUN apk add --no-cache py-pip make bash jq fish git

RUN mv $(which docker) $(which docker).old

COPY --from=docker:latest /usr/local/bin/docker /usr/local/bin/docker

ENV PS1="\h:\w\$ "
CMD bash

ARG YQ_BIN_VERSION=2.4.0
RUN wget -O /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/${YQ_BIN_VERSION}/yq_linux_amd64"

# doesn't work
RUN pip --no-cache install awscli poetry codecov
