ARG BASEIMAGE=docker:latest
FROM $BASEIMAGE as baseimage

COPY --from=docker/compose:1.24.1 /usr/local/bin/docker-compose /usr/local/bin/docker-compose

RUN apk add --no-cache python3 make bash jq fish git

ENV PS1="\h:\w\$ "
CMD bash

ARG YQ_BIN_VERSION=2.4.0
RUN wget -O /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/${YQ_BIN_VERSION}/yq_linux_amd64"

RUN pip3 --no-cache install awscli poetry codecov
